### ISSUE TITLE
[BUG] Does not consult cog.toml configuration file in repository

### ISSUE THREAD

**Issue by stephenc** [cocogitto/cocogitto-bot#9]
**Describe the bug**
We have configured our `cog.toml` with `ignore_merge_commits = true` but the bot fails if there are merge commits in the pull request

**To Reproduce**

1. Create a repo with a `cog.toml` that has `ignore_merge_commits = true`
2. Create a pull request with some commits that are valid conventional commits
3. Push some more commits to the `main` branch such that the pull request needs updating
4. Update the pull request my merging the changes from `main`, GitHub will typically create a commit with "Merge ..."
5. The bot will mark the commit as not conventional despite the `ignore_merge_commits = true` setting 

**Expected behavior**

When `cog.toml` has `ignore_merge_commits = true` then merge commits in the pull request should be ignored

**Additional context**

**Comment by oknozor** [comment]
Yes the bot needs to be updated to read the `cog.toml` conffiguration. 
Currently it does not

**Comment by the-wondersmith** [comment]
@oknozor I started tackling this over the weekend actually, and am having trouble finding a convenient place in the bot's flow to insert a check for the existence of `cog.toml` in the target codebase and subsequent check of `cog.toml`'s content if it exists.

Also I noticed [this](https://github.com/cocogitto/cocogitto-bot/blob/main/src/model/mod.rs#L37), which _looks_ like any commit whose message begins with `Merge pull request` is _supposed_ to be omitted from consideration entirely (by default), but that doesn't seem to be the real-world case from observed behavior. 🤔

Obviously respecting whatever is defined in a codebase's `cog.toml` would be the _ideal_ behavior, but _actually_ behaving as if `ignore_merge_commits` is true by default isn't a bad stop-gap (IMOFWIW).

If you'll point me in the right direction, I'll happily bang out the updated code. 😁

**Comment by the-wondersmith** [comment]
> @oknozor I started tackling this over the weekend actually, and am having trouble finding a convenient place in the bot's flow to insert a check for the existence of `cog.toml` in the target codebase and subsequent check of `cog.toml`'s content if it exists.
> 
> Also I noticed [this](https://github.com/cocogitto/cocogitto-bot/blob/main/src/model/mod.rs#L37), which _looks_ like any commit whose message begins with `Merge pull request` is _supposed_ to be omitted from consideration entirely (by default), but that doesn't seem to be the real-world case from observed behavior. 🤔
> 
> Obviously respecting whatever is defined in a codebase's `cog.toml` would be the _ideal_ behavior, but _actually_ behaving as if `ignore_merge_commits` is true by default isn't a bad stop-gap (IMOFWIW).
> 
> If you'll point me in the right direction, I'll happily bang out the updated code. 😁

@oknozor Shameless self bump

**Comment by oknozor** [comment]
hey @the-wondersmith, 
Here are the required step to get there: 
1. Get `cog.toml` using the [Github API](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content) (see: https://docs.rs/octocrab/latest/octocrab/models/repos/struct.Content.html#method.decoded_content) 
2. Use `cocogitto` as a lib instead of `conventional_commit_parser` to be able to use [verify](https://github.com/cocogitto/cocogitto/blob/36d1ea5d94d2785d5019702c3d51c734436ce3b9/src/conventional/commit.rs#L200) instead of just parsing the commit message. 

Hope that helps, let me know if you need anything!

**Comment by the-wondersmith** [comment]
@oknozor That _does_ help a ton.

I've got a decent first pass worked out, but hit a minor snag - cocogitto needs to make [`ConventionalCommitError`](https://github.com/cocogitto/cocogitto/blob/main/src/conventional/error.rs#L10) public so that the `error` field of [`CommitErrorReport`](https://github.com/cocogitto/cocogitto-bot/blob/main/src/model/report.rs#L49) can be updated to use it instead of `ParseError` from `conventional_commit_parser`.

Is that feasable?

**Comment by oknozor** [comment]
Sure we can do this, I think you should work with a local version of cocogitto and make both PR at the same time.

**Comment by the-wondersmith** [comment]
@oknozor PR's are up - [cocogitto](https://github.com/cocogitto/cocogitto/pull/309) / [cocogitto-bot](https://github.com/cocogitto/cocogitto-bot/pull/13)

I've run the tests in cocogitto itself, so I'm confident in those changes. I'm also confident in the _theory_ behind the changes in the bot codebase, but it doesn't have _tests_ so I'm not 100% confident on the best way to guarantee everything.

Also, the [`Ignored`](https://github.com/cocogitto/cocogitto-bot/pull/13/files#diff-26463dfd876f3fb7285634f24ba4972ed10fb36fba87131f42a473a2a9b1679aR10) variant of the bot's `CommitReport` enum ended up technically not being _necessary_, but it obviously exists for a reason so I've just marked it as `#[allow(dead_code)]` for the moment until you'd had a chance to render a verdict on keeping it or not.

Eager to hear your thoughts on both fronts 😁

**Comment by oknozor** [comment]
Kudos to @the-wondersmith :heart: :rocket: ! 

![screenshot-2023-08-01T11:17:40](https://github.com/cocogitto/cocogitto-bot/assets/24563836/c3dd4430-7cee-4641-a5ad-588b3b003cd7)
